### ISSUE TITLE
chore: umbra-periphery polish

### ISSUE THREAD

**Issue by mds1** [ScopeLift/umbra-protocol#333]
- Bump to latest forge-std version. This will require small refactor in `DSTestPlus`:
  - Now we `import "forge-std/Test.sol";` and `contract DSTestPlus is Test`.
  - Libraries are not inherited so still need `using stdStorage for StdStorage`. 
- Most of the current README is how to use a makefile. Let's trim that down, and add a section that describes all main contracts in this folder (right now just the batch send contract, and more will be added in the future).
- Setup CI. Suggest config file to use is below, but not sure how this is affected by the project being a subdirectory instead of at the repo root. I think you might just need a `cd` step before running the forge commands.
- Move `test/` to the root, instead of having it nested within `src/`.
- Remove the unnecessary items in the current foundry config.
- Add a CI profile that has 10k fuzz runs.
- Nit: Some spacing cleanup.
    - Functions and contracts should start on the line below their declaration. We do this in most places, but some have a blank line in between.
    - A few lines have trailing spaces we can delete.
    - Makefile spacing of commands is inconsistent. I'd suggest aligning them vertically at the `:;` or having just one space on either side of each `:;`.

## CI Setup

Suggested contents of `.github/workflows/ci.yaml` are below:

```yaml
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Build contracts
        run: |
          forge --version
          forge build --sizes
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run tests
        run: FOUNDRY_PROFILE=ci forge test
```
